FROM kasmweb/desktop-deluxe:1.12.0-rolling
USER root
# Add ksm-user to sudo 
RUN apt-get update \
    && apt-get install -y sudo \
    && echo 'kasm-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && rm -rf /var/lib/apt/list/*
RUN sed -i.bak 's/-sslOnly//' /dockerstartup/vnc_startup.sh
USER 1000
